### ISSUE TITLE
Stacktrace on `charm create`

### ISSUE THREAD

**Issue by ChrisMacNaughton** [juju/charm#253]
When I try to create a new charm with the snap version of charm, I get the following stacktrace on both cosmic and a clean xenial container. This same command worked as recently as a few days ago but is now failing

```
# charm create $charm_name
INFO: Using default charm template (reactive-python). To select a different template, use the -t option.
INFO: Generating charm for $charm_name in ./$charm_name
INFO: No $charm_name in apt cache; creating an empty charm instead.
Cloning into '/tmp/tmprs4mlcm_'...
warning: templates not found /snap/charm/158/share/git-core/templates
remote: Counting objects: 32, done.
remote: Total 32 (delta 0), reused 0 (delta 0), pack-reused 31
Unpacking objects: 100% (32/32), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "/snap/charm/158/bin/charm-create", line 9, in <module>
    load_entry_point('charm-tools==2.2.4', 'console_scripts', 'charm-create')()
  File "/snap/charm/158/lib/python3.5/site-packages/charmtools/create.py", line 98, in main
    generator.create_charm()
  File "/snap/charm/158/lib/python3.5/site-packages/charmtools/generators/generator.py", line 93, in create_charm
    self.plugin.create_charm(user_config, tempdir)
  File "/snap/charm/158/lib/python3.5/site-packages/charmtools/templates/reactive_python/template.py", line 53, in create_charm
    self._template_file(config, path.join(root, outfile))
  File "/snap/charm/158/lib/python3.5/site-packages/charmtools/templates/reactive_python/template.py", line 64, in _template_file
    o.write(str(t))
  File "/snap/charm/158/usr/lib/python3.5/tempfile.py", line 622, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by johnsca** [comment]
Also, for the record, this repo is the go library for parsing charm data and not related to `charm create`.

The `charm` CLI is comprised of https://github.com/juju/charm-tools and https://github.com/juju/charmstore-client with the latter containing the implementation of the commands that interact with the charm store (push, pull, release, grant, etc.) and the former containing the commands for creating and building charms.

I will not be able to close this issue.
